<script lang="ts">
	import { currentModel } from '$lib/stores/dateStore';

	const currentYear = new Date().getFullYear();

	$: modelName = $currentModel?.display_name ?? '';
</script>

<footer class="bg-bg-dark text-white mt-auto">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
		<div class="flex flex-col md:flex-row items-center justify-between gap-4">
			<div class="flex items-center gap-3">
				<img
					src="/assets/logo.webp"
					alt="Agent N Logo"
					class="w-8 h-8 rounded-full"
				/>
				<div>
					<p class="font-medium">Agent N's Hermes News</p>
					<p class="text-sm text-text-muted">
						{#if modelName}
							Powered by {modelName}
						{:else}
							Daily Hermes Agent news from Agent N
						{/if}
					</p>
				</div>
			</div>

			<div class="flex items-center gap-6 text-sm text-text-muted">
				<span>Agent N's Hermes News</span>
				<span>&copy; {currentYear}</span>
				<a href="/about" class="hover:text-white transition-colors">[About]</a>
				<a href="/feeds" class="hover:text-white transition-colors">[RSS]</a>
			</div>
		</div>

		<!-- AI Disclaimer -->
		<div class="border-t border-teal-border mt-4 pt-4">
			<p class="text-xs text-text-muted text-center">
				Content generated by AI. May contain errors.
				<a href="/about" class="hover:text-text-light underline">Learn more</a>
			</p>
		</div>
	</div>
</footer>
